GLOB sdist-make: /workdir/typed-ast-1.5.4/setup.py
graalpylibtest-unit-test-tests create: /workdir/typed-ast-1.5.4/.tox/graalpylibtest-unit-test-tests
graalpylibtest-unit-test-tests installdeps: mock, pytest
graalpylibtest-unit-test-tests inst: /workdir/typed-ast-1.5.4/.tox/.tmp/package/1/typed_ast-1.5.4.zip
graalpylibtest-unit-test-tests installed: exceptiongroup==1.2.0,graalpy-virtualenv==0.0.1,hpy==0.9.0rc2,iniconfig==2.0.0,mock==5.1.0,packaging==23.2,pluggy==1.3.0,pytest==7.4.3,tomli==2.0.1,typed-ast @ file:///workdir/typed-ast-1.5.4/.tox/.tmp/package/1/typed_ast-1.5.4.zip
graalpylibtest-unit-test-tests run-test-pre: PYTHONHASHSEED='971343157'
graalpylibtest-unit-test-tests run-test: commands[0] | pytest -v --tb=native --junitxml /workdir/results/typed-ast/1.5.4/1/graalpy-test-results.xml
============================= test session starts ==============================
platform linux -- Python 3.10.8, pytest-7.4.3, pluggy-1.3.0 -- /workdir/typed-ast-1.5.4/.tox/graalpylibtest-unit-test-tests/bin/python
cachedir: .tox/graalpylibtest-unit-test-tests/.pytest_cache
rootdir: /workdir/typed-ast-1.5.4
collecting ... collected 0 items / 1 error

==================================== ERRORS ====================================
__________________ ERROR collecting ast3/tests/test_basics.py __________________
ImportError while importing test module '/workdir/typed-ast-1.5.4/ast3/tests/test_basics.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
SystemError: /workdir/typed-ast-1.5.4/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/typed_ast/_ast3.graalpy231-310-native-x86_64-linux.so: undefined symbol: _PyArena_AddPyObject

The above exception was the direct cause of the following exception:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ast3/tests/test_basics.py:5: in <module>
    from typed_ast import _ast3
E   ImportError: cannot load /workdir/typed-ast-1.5.4/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/typed_ast/_ast3.graalpy231-310-native-x86_64-linux.so: NFIUnsatisfiedLinkError: /workdir/typed-ast-1.5.4/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/typed_ast/_ast3.graalpy231-310-native-x86_64-linux.so: undefined symbol: _PyArena_AddPyObject
- generated xml file: /workdir/results/typed-ast/1.5.4/1/graalpy-test-results.xml -
=========================== short test summary info ============================
ERROR ast3/tests/test_basics.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 1.62s ===============================
ERROR: InvocationError for command /workdir/typed-ast-1.5.4/.tox/graalpylibtest-unit-test-tests/bin/pytest -v --tb=native --junitxml /workdir/results/typed-ast/1.5.4/1/graalpy-test-results.xml (exited with code 2)
___________________________________ summary ____________________________________
ERROR:   graalpylibtest-unit-test-tests: commands failed
