GLOB sdist-make: /workdir/redis-4.4.0/setup.py
graalpylibtest-unit-test-tests create: /workdir/redis-4.4.0/.tox/graalpylibtest-unit-test-tests
graalpylibtest-unit-test-tests installdeps: mock, pytest, -rdev_requirements.txt, -rrequirements.txt
graalpylibtest-unit-test-tests inst: /workdir/redis-4.4.0/.tox/.tmp/package/1/redis-4.4.0.zip
graalpylibtest-unit-test-tests installed: astor==0.8.1,async-timeout==4.0.3,attrs==23.1.0,black==22.3.0,certifi==2023.11.17,charset-normalizer==3.1.0,click==8.0.4,coverage==7.3.2,distlib==0.3.7,docker==5.0.3,exceptiongroup==1.2.0,filelock==3.13.1,flake8==5.0.4,flynt==0.69,graalpy-virtualenv==0.0.1,hpy==0.9.0rc2,idna==3.6,iniconfig==2.0.0,invoke==1.7.3,isort==5.10.1,mccabe==0.7.0,mock==4.0.3,mypy-extensions==1.0.0,packaging==23.2,pathspec==0.11.2,platformdirs==4.0.0,pluggy==1.3.0,py==1.11.0,pycodestyle==2.9.1,pyflakes==2.5.0,pytest==7.2.0,pytest-asyncio==0.21.1,pytest-cov==4.1.0,pytest-timeout==2.0.1,redis @ file:///workdir/redis-4.4.0/.tox/.tmp/package/1/redis-4.4.0.zip,requests==2.31.0,six==1.16.0,toml==0.10.2,tomli==2.0.1,tox==3.27.1,tox-docker==3.1.0,ujson==5.8.0,urllib3==2.1.0,uvloop==0.19.0,virtualenv==20.24.7,vulture==2.10,websocket-client==1.6.4
graalpylibtest-unit-test-tests run-test-pre: PYTHONHASHSEED='2292685925'
graalpylibtest-unit-test-tests run-test: commands[0] | pytest -v --tb=native --junitxml /workdir/results/redis/4.4.0/1/graalpy-test-results.xml
ImportError while loading conftest '/workdir/redis-4.4.0/tests/conftest.py'.
tests/conftest.py:11: in <module>
    import redis
redis/__init__.py:4: in <module>
    from redis.client import Redis, StrictRedis
redis/client.py:10: in <module>
    from redis.commands import (
redis/commands/__init__.py:1: in <module>
    from .cluster import READ_COMMANDS, AsyncRedisClusterCommands, RedisClusterCommands
redis/commands/cluster.py:17: in <module>
    from redis.crc import key_slot
redis/crc.py:1: in <module>
    from binascii import crc_hqx
E   ImportError: cannot import name 'crc_hqx' from 'binascii' (unknown location)
ERROR: InvocationError for command /workdir/redis-4.4.0/.tox/graalpylibtest-unit-test-tests/bin/pytest -v --tb=native --junitxml /workdir/results/redis/4.4.0/1/graalpy-test-results.xml (exited with code 4)
___________________________________ summary ____________________________________
ERROR:   graalpylibtest-unit-test-tests: commands failed
