GLOB sdist-make: /workdir/pygame-2.1.2/setup.py
cpythonlibtest-unit-test-tests create: /workdir/pygame-2.1.2/.tox/cpythonlibtest-unit-test-tests
cpythonlibtest-unit-test-tests installdeps: mock, pytest
cpythonlibtest-unit-test-tests inst: /workdir/pygame-2.1.2/.tox/.tmp/package/1/pygame-2.1.2.zip
cpythonlibtest-unit-test-tests installed: exceptiongroup==1.2.0,iniconfig==2.0.0,mock==5.1.0,packaging==23.2,pluggy==1.3.0,pygame @ file:///workdir/pygame-2.1.2/.tox/.tmp/package/1/pygame-2.1.2.zip#sha256=49ec7ecdc726176129af82d92a44887a226a83a95238f1eee661813104bb077d,pytest==7.4.3,tomli==2.0.1
cpythonlibtest-unit-test-tests run-test-pre: PYTHONHASHSEED='1862408721'
cpythonlibtest-unit-test-tests run-test: commands[0] | pytest -v --tb=native --junitxml /workdir/results/pygame/2.1.2/1/cpython-test-results.xml
============================= test session starts ==============================
platform linux -- Python 3.10.8, pytest-7.4.3, pluggy-1.3.0 -- /workdir/pygame-2.1.2/.tox/cpythonlibtest-unit-test-tests/bin/python
cachedir: .tox/cpythonlibtest-unit-test-tests/.pytest_cache
rootdir: /workdir/pygame-2.1.2
collecting ... 
********************************************************************************
Timeout exceeded, sending SIGINT to process
********************************************************************************
*** Timed out after 0:05:00
