GLOB sdist-make: /workdir/bump2version-1.0.1/setup.py
cpythonlibtest-unit-test-tests create: /workdir/bump2version-1.0.1/.tox/cpythonlibtest-unit-test-tests
cpythonlibtest-unit-test-tests installdeps: mock, pytest
cpythonlibtest-unit-test-tests inst: /workdir/bump2version-1.0.1/.tox/.tmp/package/1/bump2version-1.0.1.zip
cpythonlibtest-unit-test-tests installed: bump2version @ file:///workdir/bump2version-1.0.1/.tox/.tmp/package/1/bump2version-1.0.1.zip#sha256=d7c7aa0d5d8c90dc7d9bd5e0c368b5c9333a222541ff7ed782818f8c4c6a743d,exceptiongroup==1.1.3,iniconfig==2.0.0,mock==5.1.0,packaging==23.2,pluggy==1.3.0,pytest==7.4.3,tomli==2.0.1
cpythonlibtest-unit-test-tests run-test-pre: PYTHONHASHSEED='3614105353'
cpythonlibtest-unit-test-tests run-test: commands[0] | pytest -v --tb=native --junitxml /workdir/results/bump2version/1.0.1/1/cpython-test-results.xml
============================= test session starts ==============================
platform linux -- Python 3.10.8, pytest-7.4.3, pluggy-1.3.0 -- /workdir/bump2version-1.0.1/.tox/cpythonlibtest-unit-test-tests/bin/python
cachedir: .tox/cpythonlibtest-unit-test-tests/.pytest_cache
rootdir: /workdir/bump2version-1.0.1
configfile: tox.ini
collecting ... collected 37 items / 1 error

==================================== ERRORS ====================================
______________________ ERROR collecting tests/test_cli.py ______________________
ImportError while importing test module '/workdir/bump2version-1.0.1/tests/test_cli.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_cli.py:15: in <module>
    from testfixtures import LogCapture
E   ModuleNotFoundError: No module named 'testfixtures'
- generated xml file: /workdir/results/bump2version/1.0.1/1/cpython-test-results.xml -
=========================== short test summary info ============================
ERROR tests/test_cli.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.28s ===============================
ERROR: InvocationError for command /workdir/bump2version-1.0.1/.tox/cpythonlibtest-unit-test-tests/bin/pytest -v --tb=native --junitxml /workdir/results/bump2version/1.0.1/1/cpython-test-results.xml (exited with code 2)
___________________________________ summary ____________________________________
ERROR:   cpythonlibtest-unit-test-tests: commands failed
