GLOB sdist-make: /workdir/commonmark-0.9.1/setup.py
cpythonlibtest-unit-test-tests create: /workdir/commonmark-0.9.1/.tox/cpythonlibtest-unit-test-tests
cpythonlibtest-unit-test-tests installdeps: mock, pytest
cpythonlibtest-unit-test-tests inst: /workdir/commonmark-0.9.1/.tox/.tmp/package/1/commonmark-0.9.1.zip
cpythonlibtest-unit-test-tests installed: commonmark @ file:///workdir/commonmark-0.9.1/.tox/.tmp/package/1/commonmark-0.9.1.zip#sha256=902cbcd8301cec431d81e28b95af08c2b9ecdd6f1197f66787ead8e1dad854d9,exceptiongroup==1.1.3,iniconfig==2.0.0,mock==5.1.0,packaging==23.2,pluggy==1.3.0,pytest==7.4.3,tomli==2.0.1
cpythonlibtest-unit-test-tests run-test-pre: PYTHONHASHSEED='2520868475'
cpythonlibtest-unit-test-tests run-test: commands[0] | pytest -v --tb=native --junitxml /workdir/results/commonmark/0.9.1/1/cpython-test-results.xml
============================= test session starts ==============================
platform linux -- Python 3.10.8, pytest-7.4.3, pluggy-1.3.0 -- /workdir/commonmark-0.9.1/.tox/cpythonlibtest-unit-test-tests/bin/python
cachedir: .tox/cpythonlibtest-unit-test-tests/.pytest_cache
rootdir: /workdir/commonmark-0.9.1
collecting ... collected 0 items

- generated xml file: /workdir/results/commonmark/0.9.1/1/cpython-test-results.xml -
============================ no tests ran in 0.02s =============================
ERROR: InvocationError for command /workdir/commonmark-0.9.1/.tox/cpythonlibtest-unit-test-tests/bin/pytest -v --tb=native --junitxml /workdir/results/commonmark/0.9.1/1/cpython-test-results.xml (exited with code 5)
___________________________________ summary ____________________________________
ERROR:   cpythonlibtest-unit-test-tests: commands failed
