GLOB sdist-make: /workdir/qrcode-7.3.1/setup.py
cpythonlibtest-unit-test-tests create: /workdir/qrcode-7.3.1/.tox/cpythonlibtest-unit-test-tests
cpythonlibtest-unit-test-tests installdeps: mock, pytest
cpythonlibtest-unit-test-tests inst: /workdir/qrcode-7.3.1/.tox/.tmp/package/1/qrcode-7.3.1.zip
cpythonlibtest-unit-test-tests installed: exceptiongroup==1.2.0,iniconfig==2.0.0,mock==5.1.0,packaging==23.2,pluggy==1.3.0,pytest==7.4.3,qrcode @ file:///workdir/qrcode-7.3.1/.tox/.tmp/package/1/qrcode-7.3.1.zip#sha256=4bc6d306489739fa24275662217befe1d339b29a6f348ec5bd2f37cb3947b5d1,tomli==2.0.1
cpythonlibtest-unit-test-tests run-test-pre: PYTHONHASHSEED='18121934'
cpythonlibtest-unit-test-tests run-test: commands[0] | pytest -v --tb=native --junitxml /workdir/results/qrcode/7.3.1/1/cpython-test-results.xml
============================= test session starts ==============================
platform linux -- Python 3.10.8, pytest-7.4.3, pluggy-1.3.0 -- /workdir/qrcode-7.3.1/.tox/cpythonlibtest-unit-test-tests/bin/python
cachedir: .tox/cpythonlibtest-unit-test-tests/.pytest_cache
rootdir: /workdir/qrcode-7.3.1
configfile: setup.cfg
collecting ... collected 14 items / 1 error

==================================== ERRORS ====================================
_________________ ERROR collecting qrcode/tests/test_qrcode.py _________________
ImportError while importing test module '/workdir/qrcode-7.3.1/qrcode/tests/test_qrcode.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
qrcode/image/pil.py:5: in <module>
    from PIL import Image, ImageDraw
E   ModuleNotFoundError: No module named 'PIL'

During handling of the above exception, another exception occurred:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
qrcode/tests/test_qrcode.py:20: in <module>
    from qrcode.image.pil import Image as pil_Image
qrcode/image/pil.py:7: in <module>
    import Image
E   ModuleNotFoundError: No module named 'Image'
- generated xml file: /workdir/results/qrcode/7.3.1/1/cpython-test-results.xml -
=========================== short test summary info ============================
ERROR qrcode/tests/test_qrcode.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.12s ===============================
ERROR: InvocationError for command /workdir/qrcode-7.3.1/.tox/cpythonlibtest-unit-test-tests/bin/pytest -v --tb=native --junitxml /workdir/results/qrcode/7.3.1/1/cpython-test-results.xml (exited with code 2)
___________________________________ summary ____________________________________
ERROR:   cpythonlibtest-unit-test-tests: commands failed
