GLOB sdist-make: /workdir/numpy-1.23.5/setup.py
cpythonlibtest-unit-test-tests create: /workdir/numpy-1.23.5/.tox/cpythonlibtest-unit-test-tests
cpythonlibtest-unit-test-tests installdeps: mock, unittest-xml-reporting, -rrelease_requirements.txt, -rtest_requirements.txt, -rlinter_requirements.txt, -rdoc_requirements.txt
cpythonlibtest-unit-test-tests inst: /workdir/numpy-1.23.5/.tox/.tmp/package/1/numpy-1.23.5.zip
cpythonlibtest-unit-test-tests installed: alabaster==0.7.13,asttokens==2.4.1,attrs==23.1.0,Babel==2.13.1,beautifulsoup4==4.12.2,breathe==4.35.0,certifi==2023.11.17,cffi==1.16.0,charset-normalizer==3.3.2,click==8.1.7,click-default-group==1.2.4,contourpy==1.2.0,coverage==7.3.2,cryptography==41.0.5,cycler==0.12.1,Cython==0.29.36,decorator==5.1.1,Deprecated==1.2.14,docutils==0.17.1,exceptiongroup==1.2.0,executing==2.0.1,fonttools==4.45.0,gitdb==4.0.11,GitPython==3.1.13,hypothesis==6.24.1,idna==3.4,imagesize==1.4.1,importlib-metadata==6.8.0,incremental==22.10.0,iniconfig==2.0.0,ipython==8.17.2,jaraco.classes==3.3.0,jedi==0.19.1,jeepney==0.8.0,Jinja2==3.1.2,keyring==24.3.0,kiwisolver==1.4.5,lxml==4.9.3,markdown-it-py==3.0.0,MarkupSafe==2.1.3,matplotlib==3.8.2,matplotlib-inline==0.1.6,mdurl==0.1.2,mock==5.1.0,more-itertools==10.1.0,mypy==0.981,mypy-extensions==1.0.0,nh3==0.2.14,numpy @ file:///workdir/numpy-1.23.5/.tox/.tmp/package/1/numpy-1.23.5.zip#sha256=add3b0f956f8806bbaf161e7e229f8826af9fb2616fa50c7dc10da4ffac29f8e,numpydoc==1.3.1,packaging==23.2,pandas==2.1.3,parso==0.8.3,Paver==1.3.4,pexpect==4.8.0,Pillow==10.1.0,pkginfo==1.9.6,pluggy==1.3.0,prompt-toolkit==3.0.41,ptyprocess==0.7.0,pure-eval==0.2.2,py==1.11.0,pycodestyle==2.8.0,pycparser==2.21,pydata-sphinx-theme==0.8.1,PyGithub==2.1.1,Pygments==2.17.2,PyJWT==2.8.0,PyNaCl==1.5.0,pyparsing==3.1.1,pytest==6.2.5,pytest-cov==3.0.0,python-dateutil==2.8.2,pytz==2021.3,readme-renderer==42.0,requests==2.31.0,requests-toolbelt==1.0.0,rfc3986==2.0.0,rich==13.7.0,scipy==1.11.4,SecretStorage==3.3.3,six==1.16.0,smmap==5.0.1,snowballstemmer==2.2.0,sortedcontainers==2.4.0,soupsieve==2.5,Sphinx==4.5.0,sphinx-panels==0.6.0,sphinxcontrib-applehelp==1.0.4,sphinxcontrib-devhelp==1.0.2,sphinxcontrib-htmlhelp==2.0.1,sphinxcontrib-jsmath==1.0.1,sphinxcontrib-qthelp==1.0.3,sphinxcontrib-serializinghtml==1.1.5,stack-data==0.6.3,toml==0.10.2,tomli==2.0.1,towncrier==21.9.0,traitlets==5.13.0,twine==4.0.2,typing_extensions==4.8.0,tzdata==2023.3,unittest-xml-reporting==3.2.0,urllib3==2.1.0,wcwidth==0.2.12,wrapt==1.16.0,zipp==3.17.0
cpythonlibtest-unit-test-tests run-test-pre: PYTHONHASHSEED='4244350019'
cpythonlibtest-unit-test-tests run-test: commands[0] | /workdir/numpy-1.23.5/.tox/cpythonlibtest-unit-test-tests/bin/python -m xmlrunner --output-file /workdir/results/numpy/1.23.5/1/cpython-test-results.xml

Running tests...
----------------------------------------------------------------------
E
======================================================================
ERROR [0.009s]: numpy (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: numpy
Traceback (most recent call last):
  File "/workdir/numpy-1.23.5/numpy/__init__.py", line 124, in <module>
    from numpy.__config__ import show as show_config
ModuleNotFoundError: No module named 'numpy.__config__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/workdir/numpy-1.23.5/numpy/__init__.py", line 129, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.


----------------------------------------------------------------------
Ran 1 test in 0.009s

FAILED (errors=1)

Generating XML reports...
ERROR: InvocationError for command /workdir/numpy-1.23.5/.tox/cpythonlibtest-unit-test-tests/bin/python -m xmlrunner --output-file /workdir/results/numpy/1.23.5/1/cpython-test-results.xml (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   cpythonlibtest-unit-test-tests: commands failed
