<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
	<testsuite name="unittest.loader._FailedTest-20231120210625" tests="1" file="unittest/loader.py" time="0.003" timestamp="2023-11-20T21:06:25" failures="0" errors="1" skipped="0">
		<testcase classname="unittest.loader._FailedTest.test" name="test" time="0.003" timestamp="2023-11-20T21:06:25" file="/usr/local/lib/python3.10/unittest/loader.py" line="33">
			<error type="ImportError" message="Failed to import test module: test.test
Traceback (most recent call last):
  File &quot;/usr/local/lib/python3.10/unittest/loader.py&quot;, line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File &quot;/usr/local/lib/python3.10/unittest/loader.py&quot;, line 377, in _get_module_from_name
    __import__(name)
  File &quot;/workdir/argcomplete-2.0.0/test/test.py&quot;, line 7, in &lt;module&gt;
    import pexpect, pexpect.replwrap
ModuleNotFoundError: No module named 'pexpect'
"><![CDATA[ImportError: Failed to import test module: test.test
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/workdir/argcomplete-2.0.0/test/test.py", line 7, in <module>
    import pexpect, pexpect.replwrap
ModuleNotFoundError: No module named 'pexpect'

]]></error>
		</testcase>
	</testsuite>
</testsuites>
