GLOB sdist-make: /workdir/netifaces-0.11.0/setup.py
cpythonlibtest-unit-test-tests create: /workdir/netifaces-0.11.0/.tox/cpythonlibtest-unit-test-tests
cpythonlibtest-unit-test-tests installdeps: mock, pytest
cpythonlibtest-unit-test-tests inst: /workdir/netifaces-0.11.0/.tox/.tmp/package/1/netifaces-0.11.0.zip
cpythonlibtest-unit-test-tests installed: exceptiongroup==1.2.0,iniconfig==2.0.0,mock==5.1.0,netifaces @ file:///workdir/netifaces-0.11.0/.tox/.tmp/package/1/netifaces-0.11.0.zip#sha256=b36937c6788fb69ece28ec1d6fe82a27d564502e516681d4b1312cf8a407b2d2,packaging==23.2,pluggy==1.3.0,pytest==7.4.3,tomli==2.0.1
cpythonlibtest-unit-test-tests run-test-pre: PYTHONHASHSEED='206305490'
cpythonlibtest-unit-test-tests run-test: commands[0] | pytest -v --tb=native --junitxml /workdir/results/netifaces/0.11.0/1/cpython-test-results.xml
============================= test session starts ==============================
platform linux -- Python 3.10.8, pytest-7.4.3, pluggy-1.3.0 -- /workdir/netifaces-0.11.0/.tox/cpythonlibtest-unit-test-tests/bin/python
cachedir: .tox/cpythonlibtest-unit-test-tests/.pytest_cache
rootdir: /workdir/netifaces-0.11.0
collecting ... collected 0 items

- generated xml file: /workdir/results/netifaces/0.11.0/1/cpython-test-results.xml -
============================ no tests ran in 0.01s =============================
ERROR: InvocationError for command /workdir/netifaces-0.11.0/.tox/cpythonlibtest-unit-test-tests/bin/pytest -v --tb=native --junitxml /workdir/results/netifaces/0.11.0/1/cpython-test-results.xml (exited with code 5)
___________________________________ summary ____________________________________
ERROR:   cpythonlibtest-unit-test-tests: commands failed
