GLOB sdist-make: /workdir/gitdb-4.0.10/setup.py
graalpylibtest-unit-test-tests create: /workdir/gitdb-4.0.10/.tox/graalpylibtest-unit-test-tests
graalpylibtest-unit-test-tests installdeps: mock, pytest, -rrequirements.txt
graalpylibtest-unit-test-tests inst: /workdir/gitdb-4.0.10/.tox/.tmp/package/1/gitdb-4.0.10.zip
graalpylibtest-unit-test-tests installed: exceptiongroup==1.2.0,gitdb @ file:///workdir/gitdb-4.0.10/.tox/.tmp/package/1/gitdb-4.0.10.zip,graalpy-virtualenv==0.0.1,hpy==0.9.0rc2,iniconfig==2.0.0,mock==5.1.0,packaging==23.2,pluggy==1.3.0,pytest==7.4.3,smmap==5.0.1,tomli==2.0.1
graalpylibtest-unit-test-tests run-test-pre: PYTHONHASHSEED='4059058589'
graalpylibtest-unit-test-tests run-test: commands[0] | pytest -v --tb=native --junitxml /workdir/results/gitdb/4.0.10/1/graalpy-test-results.xml
============================= test session starts ==============================
platform linux -- Python 3.10.8, pytest-7.4.3, pluggy-1.3.0 -- /workdir/gitdb-4.0.10/.tox/graalpylibtest-unit-test-tests/bin/python
cachedir: .tox/graalpylibtest-unit-test-tests/.pytest_cache
rootdir: /workdir/gitdb-4.0.10
collecting ... collected 33 items

gitdb/ext/smmap/smmap/test/test_buf.py::TestBuf::test_basics FAILED      [  3%]
gitdb/ext/smmap/smmap/test/test_mman.py::TestMMan::test_cursor PASSED    [  6%]
gitdb/ext/smmap/smmap/test/test_mman.py::TestMMan::test_memman_operation PASSED [  9%]
gitdb/ext/smmap/smmap/test/test_mman.py::TestMMan::test_memory_manager PASSED [ 12%]
gitdb/ext/smmap/smmap/test/test_tutorial.py::TestTutorial::test_example PASSED [ 15%]
gitdb/ext/smmap/smmap/test/test_util.py::TestMMan::test_region PASSED    [ 18%]
gitdb/ext/smmap/smmap/test/test_util.py::TestMMan::test_region_list PASSED [ 21%]
gitdb/ext/smmap/smmap/test/test_util.py::TestMMan::test_util PASSED      [ 24%]
gitdb/ext/smmap/smmap/test/test_util.py::TestMMan::test_window PASSED    [ 27%]
gitdb/test/test_base.py::TestBaseTypes::test_streams PASSED              [ 30%]
gitdb/test/test_example.py::TestExamples::test_base PASSED               [ 33%]
gitdb/test/test_pack.py::TestPack::test_pack FAILED                      [ 36%]
gitdb/test/test_pack.py::TestPack::test_pack_64 SKIPPED (not impleme...) [ 39%]
gitdb/test/test_pack.py::TestPack::test_pack_entity PASSED               [ 42%]
gitdb/test/test_pack.py::TestPack::test_pack_index PASSED                [ 45%]
gitdb/test/test_stream.py::TestStream::test_compressed_writer PASSED     [ 48%]
gitdb/test/test_stream.py::TestStream::test_decompress_reader FAILED     [ 51%]
gitdb/test/test_stream.py::TestStream::test_decompress_reader_special_case PASSED [ 54%]
gitdb/test/test_stream.py::TestStream::test_sha_writer PASSED            [ 57%]
gitdb/test/test_util.py::TestUtils::test_basics PASSED                   [ 60%]
gitdb/test/test_util.py::TestUtils::test_lockedfd FAILED                 [ 63%]
gitdb/test/db/test_git.py::TestGitDB::test_reading PASSED                [ 66%]
gitdb/test/db/test_git.py::TestGitDB::test_writing PASSED                [ 69%]
gitdb/test/db/test_loose.py::TestLooseDB::test_basics PASSED             [ 72%]
gitdb/test/db/test_mem.py::TestMemoryDB::test_writing PASSED             [ 75%]
gitdb/test/db/test_pack.py::TestPackDB::test_writing PASSED              [ 78%]
gitdb/test/db/test_ref.py::TestReferenceDB::test_writing PASSED          [ 81%]
gitdb/test/performance/test_pack.py::TestPackedDBPerformance::test_correctness PASSED [ 84%]
gitdb/test/performance/test_pack.py::TestPackedDBPerformance::test_loose_correctness PASSED [ 87%]
gitdb/test/performance/test_pack.py::TestPackedDBPerformance::test_pack_random_access PASSED [ 90%]
gitdb/test/performance/test_pack_streaming.py::TestPackStreamingPerformance::test_pack_writing PASSED [ 93%]
gitdb/test/performance/test_pack_streaming.py::TestPackStreamingPerformance::test_stream_reading PASSED [ 96%]
gitdb/test/performance/test_stream.py::TestObjDBPerformance::test_large_data_streaming PASSED [100%]

=================================== FAILURES ===================================
_____________________________ TestBuf.test_basics ______________________________
Traceback (most recent call last):
  File "/opt/graalpy/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/opt/graalpy/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/opt/graalpy/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/workdir/gitdb-4.0.10/gitdb/ext/smmap/smmap/test/test_buf.py", line 114, in test_basics
    assert manager.collect()
AssertionError
______________________________ TestPack.test_pack ______________________________
Traceback (most recent call last):
  File "/opt/graalpy/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/opt/graalpy/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/opt/graalpy/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/workdir/gitdb-4.0.10/gitdb/test/test_pack.py", line 135, in test_pack
    self._assert_pack_file(pack, version, size)
  File "/workdir/gitdb-4.0.10/gitdb/test/test_pack.py", line 84, in _assert_pack_file
    for obj in pack.stream_iter():
  File "/workdir/gitdb-4.0.10/gitdb/pack.py", line 556, in _iter_objects
    stream_copy(ostream.read, null.write, ostream.size, chunk_size)
  File "/workdir/gitdb-4.0.10/gitdb/fun.py", line 525, in stream_copy
    data = read(cs)
  File "/workdir/gitdb-4.0.10/gitdb/base.py", line 176, in read
    return self[3].read(size)
  File "/workdir/gitdb-4.0.10/gitdb/stream.py", line 283, in read
    dcompdat = self._zip.decompress(indata, size)
zlib.error: Error -3 while decompressing data: incorrect header check
______________________ TestStream.test_decompress_reader _______________________
Traceback (most recent call last):
  File "/opt/graalpy/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/opt/graalpy/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/opt/graalpy/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/workdir/gitdb-4.0.10/gitdb/test/test_stream.py", line 111, in test_decompress_reader
    assert dummy.closed == close_on_deletion
AssertionError
___________________________ TestUtils.test_lockedfd ____________________________
Traceback (most recent call last):
  File "/opt/graalpy/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/opt/graalpy/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/opt/graalpy/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/workdir/gitdb-4.0.10/gitdb/test/test_util.py", line 71, in test_lockedfd
    assert not os.path.isfile(lockfilepath)
AssertionError
- generated xml file: /workdir/results/gitdb/4.0.10/1/graalpy-test-results.xml -
=========================== short test summary info ============================
FAILED gitdb/ext/smmap/smmap/test/test_buf.py::TestBuf::test_basics - Asserti...
FAILED gitdb/test/test_pack.py::TestPack::test_pack - zlib.error: Error -3 wh...
FAILED gitdb/test/test_stream.py::TestStream::test_decompress_reader - Assert...
FAILED gitdb/test/test_util.py::TestUtils::test_lockedfd - AssertionError
============== 4 failed, 28 passed, 1 skipped in 82.18s (0:01:22) ==============
ERROR: InvocationError for command /workdir/gitdb-4.0.10/.tox/graalpylibtest-unit-test-tests/bin/pytest -v --tb=native --junitxml /workdir/results/gitdb/4.0.10/1/graalpy-test-results.xml (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   graalpylibtest-unit-test-tests: commands failed
