.package create: /workdir/django-filter-22.1/.tox/.package
.package installdeps: setuptools, wheel
/workdir/django-filter-22.1/.tox/.package/lib/python3.10/site-packages/setuptools/config/setupcfg.py:463: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
  warnings.warn(msg, warning_class)
no previously-included directories found matching 'docs/_build'
warning: no previously-included files matching '__pycache__' found anywhere in distribution
warning: no previously-included files matching '*.py[co]' found anywhere in distribution
/workdir/django-filter-22.1/.tox/.package/lib/python3.10/site-packages/setuptools/config/setupcfg.py:463: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
  warnings.warn(msg, warning_class)
no previously-included directories found matching 'docs/_build'
warning: no previously-included files matching '__pycache__' found anywhere in distribution
warning: no previously-included files matching '*.py[co]' found anywhere in distribution
cpythonlibtest-unit-test-tests create: /workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests
cpythonlibtest-unit-test-tests installdeps: mock, pytest, -rrequirements/test-ci.txt, -rrequirements/maintainer.txt, -rrequirements/test.txt
cpythonlibtest-unit-test-tests inst: /workdir/django-filter-22.1/.tox/.tmp/package/1/django-filter-22.1.tar.gz
cpythonlibtest-unit-test-tests installed: alabaster==0.7.13,asgiref==3.7.2,Babel==2.13.1,certifi==2023.11.17,cffi==1.16.0,charset-normalizer==3.3.2,coreapi==2.3.3,coreschema==0.0.4,coverage==7.3.2,cryptography==41.0.5,Django==4.2.7,django-crispy-forms==2.1,django-filter @ file:///workdir/django-filter-22.1/.tox/.tmp/package/1/django-filter-22.1.tar.gz#sha256=ea38e06227d0c00e555b338c8648ae9dccb33047ab98c94177ea33e1f2c0a7f5,djangorestframework==3.14.0,docutils==0.20.1,exceptiongroup==1.1.3,idna==3.4,imagesize==1.4.1,importlib-metadata==6.8.0,iniconfig==2.0.0,itypes==1.2.0,jaraco.classes==3.3.0,jeepney==0.8.0,Jinja2==3.1.2,keyring==24.3.0,lxml==4.9.3,Markdown==3.5.1,markdown-it-py==3.0.0,MarkupSafe==2.1.3,mdurl==0.1.2,mock==5.1.0,more-itertools==10.1.0,nh3==0.2.14,packaging==23.2,pkginfo==1.9.6,pluggy==1.3.0,pycparser==2.21,Pygments==2.17.1,pytest==7.4.3,pytz==2023.3.post1,readme-renderer==42.0,requests==2.31.0,requests-toolbelt==1.0.0,rfc3986==2.0.0,rich==13.7.0,SecretStorage==3.3.3,snowballstemmer==2.2.0,Sphinx==7.2.6,sphinxcontrib-applehelp==1.0.7,sphinxcontrib-devhelp==1.0.5,sphinxcontrib-htmlhelp==2.0.4,sphinxcontrib-jsmath==1.0.1,sphinxcontrib-qthelp==1.0.6,sphinxcontrib-serializinghtml==1.1.9,sqlparse==0.4.4,tomli==2.0.1,twine==4.0.2,typing_extensions==4.8.0,unittest-xml-reporting==3.2.0,uritemplate==4.1.1,urllib3==2.1.0,zipp==3.17.0
cpythonlibtest-unit-test-tests run-test-pre: PYTHONHASHSEED='4003818225'
cpythonlibtest-unit-test-tests run-test: commands[0] | pytest -v --tb=native --junitxml /workdir/results/django-filter/22.1/1/cpython-test-results.xml
============================= test session starts ==============================
platform linux -- Python 3.10.8, pytest-7.4.3, pluggy-1.3.0 -- /workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/bin/python
cachedir: .tox/cpythonlibtest-unit-test-tests/.pytest_cache
rootdir: /workdir/django-filter-22.1
collecting ... collected 68 items / 9 errors

==================================== ERRORS ====================================
___________________ ERROR collecting tests/test_filtering.py ___________________
Traceback (most recent call last):
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 372, in <lambda>
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 531, in collect
    self._inject_setup_module_fixture()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 545, in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 310, in obj
    self._obj = obj = self._getobj()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 528, in _getobj
    return self._importtestmodule()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 617, in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/pathlib.py", line 567, in import_path
    importlib.import_module(module_name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 186, in exec_module
    exec(co, module.__dict__)
  File "/workdir/django-filter-22.1/tests/test_filtering.py", line 34, in <module>
    from .models import (
  File "/workdir/django-filter-22.1/tests/models.py", line 42, in <module>
    class User(models.Model):
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/db/models/base.py", line 129, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/apps/registry.py", line 260, in get_containing_app_config
    self.check_apps_ready()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/apps/registry.py", line 137, in check_apps_ready
    settings.INSTALLED_APPS
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/conf/__init__.py", line 82, in _setup
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
____________________ ERROR collecting tests/test_filters.py ____________________
Traceback (most recent call last):
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 372, in <lambda>
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 531, in collect
    self._inject_setup_module_fixture()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 545, in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 310, in obj
    self._obj = obj = self._getobj()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 528, in _getobj
    return self._importtestmodule()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 617, in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/pathlib.py", line 567, in import_path
    importlib.import_module(module_name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 186, in exec_module
    exec(co, module.__dict__)
  File "/workdir/django-filter-22.1/tests/test_filters.py", line 50, in <module>
    from tests.models import Book, User
  File "/workdir/django-filter-22.1/tests/models.py", line 42, in <module>
    class User(models.Model):
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/db/models/base.py", line 129, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/apps/registry.py", line 260, in get_containing_app_config
    self.check_apps_ready()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/apps/registry.py", line 137, in check_apps_ready
    settings.INSTALLED_APPS
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/conf/__init__.py", line 82, in _setup
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
___________________ ERROR collecting tests/test_filterset.py ___________________
Traceback (most recent call last):
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 372, in <lambda>
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 531, in collect
    self._inject_setup_module_fixture()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 545, in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 310, in obj
    self._obj = obj = self._getobj()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 528, in _getobj
    return self._importtestmodule()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 617, in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/pathlib.py", line 567, in import_path
    importlib.import_module(module_name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 186, in exec_module
    exec(co, module.__dict__)
  File "/workdir/django-filter-22.1/tests/test_filterset.py", line 25, in <module>
    from .models import (
  File "/workdir/django-filter-22.1/tests/models.py", line 42, in <module>
    class User(models.Model):
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/db/models/base.py", line 129, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/apps/registry.py", line 260, in get_containing_app_config
    self.check_apps_ready()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/apps/registry.py", line 137, in check_apps_ready
    settings.INSTALLED_APPS
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/conf/__init__.py", line 82, in _setup
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
_____________________ ERROR collecting tests/test_forms.py _____________________
Traceback (most recent call last):
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 372, in <lambda>
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 531, in collect
    self._inject_setup_module_fixture()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 545, in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 310, in obj
    self._obj = obj = self._getobj()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 528, in _getobj
    return self._importtestmodule()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 617, in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/pathlib.py", line 567, in import_path
    importlib.import_module(module_name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 186, in exec_module
    exec(co, module.__dict__)
  File "/workdir/django-filter-22.1/tests/test_forms.py", line 7, in <module>
    from .models import MANAGER, REGULAR, STATUS_CHOICES, Book, ManagerGroup, User
  File "/workdir/django-filter-22.1/tests/models.py", line 42, in <module>
    class User(models.Model):
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/db/models/base.py", line 129, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/apps/registry.py", line 260, in get_containing_app_config
    self.check_apps_ready()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/apps/registry.py", line 137, in check_apps_ready
    settings.INSTALLED_APPS
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/conf/__init__.py", line 82, in _setup
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
_____________________ ERROR collecting tests/test_utils.py _____________________
Traceback (most recent call last):
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 372, in <lambda>
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 531, in collect
    self._inject_setup_module_fixture()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 545, in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 310, in obj
    self._obj = obj = self._getobj()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 528, in _getobj
    return self._importtestmodule()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 617, in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/pathlib.py", line 567, in import_path
    importlib.import_module(module_name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 186, in exec_module
    exec(co, module.__dict__)
  File "/workdir/django-filter-22.1/tests/test_utils.py", line 27, in <module>
    from .models import Article, Book, Business, Company, HiredWorker, NetworkSetting, User
  File "/workdir/django-filter-22.1/tests/models.py", line 42, in <module>
    class User(models.Model):
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/db/models/base.py", line 129, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/apps/registry.py", line 260, in get_containing_app_config
    self.check_apps_ready()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/apps/registry.py", line 137, in check_apps_ready
    settings.INSTALLED_APPS
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/conf/__init__.py", line 82, in _setup
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
_____________________ ERROR collecting tests/test_views.py _____________________
Traceback (most recent call last):
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 372, in <lambda>
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 531, in collect
    self._inject_setup_module_fixture()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 545, in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 310, in obj
    self._obj = obj = self._getobj()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 528, in _getobj
    return self._importtestmodule()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 617, in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/pathlib.py", line 567, in import_path
    importlib.import_module(module_name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 186, in exec_module
    exec(co, module.__dict__)
  File "/workdir/django-filter-22.1/tests/test_views.py", line 9, in <module>
    from .models import Book
  File "/workdir/django-filter-22.1/tests/models.py", line 42, in <module>
    class User(models.Model):
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/db/models/base.py", line 129, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/apps/registry.py", line 260, in get_containing_app_config
    self.check_apps_ready()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/apps/registry.py", line 137, in check_apps_ready
    settings.INSTALLED_APPS
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/conf/__init__.py", line 82, in _setup
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
____________ ERROR collecting tests/rest_framework/test_backends.py ____________
Traceback (most recent call last):
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 372, in <lambda>
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 531, in collect
    self._inject_setup_module_fixture()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 545, in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 310, in obj
    self._obj = obj = self._getobj()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 528, in _getobj
    return self._importtestmodule()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 617, in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/pathlib.py", line 567, in import_path
    importlib.import_module(module_name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 186, in exec_module
    exec(co, module.__dict__)
  File "/workdir/django-filter-22.1/tests/rest_framework/test_backends.py", line 7, in <module>
    from rest_framework import generics, serializers
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/rest_framework/generics.py", line 9, in <module>
    from rest_framework import mixins, views
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/rest_framework/views.py", line 17, in <module>
    from rest_framework.schemas import DefaultSchema
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/rest_framework/schemas/__init__.py", line 25, in <module>
    from . import coreapi, openapi
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/rest_framework/schemas/openapi.py", line 15, in <module>
    from rest_framework import (
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/rest_framework/renderers.py", line 52, in <module>
    class JSONRenderer(BaseRenderer):
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/rest_framework/renderers.py", line 59, in JSONRenderer
    ensure_ascii = not api_settings.UNICODE_JSON
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/rest_framework/settings.py", line 218, in __getattr__
    val = self.user_settings[attr]
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/rest_framework/settings.py", line 209, in user_settings
    self._user_settings = getattr(settings, 'REST_FRAMEWORK', {})
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/conf/__init__.py", line 82, in _setup
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Requested setting REST_FRAMEWORK, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
___________ ERROR collecting tests/rest_framework/test_filterset.py ____________
Traceback (most recent call last):
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 372, in <lambda>
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 531, in collect
    self._inject_setup_module_fixture()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 545, in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 310, in obj
    self._obj = obj = self._getobj()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 528, in _getobj
    return self._importtestmodule()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 617, in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/pathlib.py", line 567, in import_path
    importlib.import_module(module_name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 186, in exec_module
    exec(co, module.__dict__)
  File "/workdir/django-filter-22.1/tests/rest_framework/test_filterset.py", line 11, in <module>
    from ..models import Article, User
  File "/workdir/django-filter-22.1/tests/models.py", line 42, in <module>
    class User(models.Model):
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/db/models/base.py", line 129, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/apps/registry.py", line 260, in get_containing_app_config
    self.check_apps_ready()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/apps/registry.py", line 137, in check_apps_ready
    settings.INSTALLED_APPS
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/conf/__init__.py", line 82, in _setup
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
__________ ERROR collecting tests/rest_framework/test_integration.py ___________
Traceback (most recent call last):
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 372, in <lambda>
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 531, in collect
    self._inject_setup_module_fixture()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 545, in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 310, in obj
    self._obj = obj = self._getobj()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 528, in _getobj
    return self._importtestmodule()
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 617, in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/pathlib.py", line 567, in import_path
    importlib.import_module(module_name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 186, in exec_module
    exec(co, module.__dict__)
  File "/workdir/django-filter-22.1/tests/rest_framework/test_integration.py", line 8, in <module>
    from rest_framework import generics, serializers, status
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/rest_framework/generics.py", line 9, in <module>
    from rest_framework import mixins, views
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/rest_framework/views.py", line 17, in <module>
    from rest_framework.schemas import DefaultSchema
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/rest_framework/schemas/__init__.py", line 25, in <module>
    from . import coreapi, openapi
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/rest_framework/schemas/openapi.py", line 15, in <module>
    from rest_framework import (
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/rest_framework/renderers.py", line 52, in <module>
    class JSONRenderer(BaseRenderer):
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/rest_framework/renderers.py", line 59, in JSONRenderer
    ensure_ascii = not api_settings.UNICODE_JSON
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/rest_framework/settings.py", line 218, in __getattr__
    val = self.user_settings[attr]
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/rest_framework/settings.py", line 209, in user_settings
    self._user_settings = getattr(settings, 'REST_FRAMEWORK', {})
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/django/conf/__init__.py", line 82, in _setup
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Requested setting REST_FRAMEWORK, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
=============================== warnings summary ===============================
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/coreapi/utils.py:5
  /workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/coreapi/utils.py:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    import pkg_resources

.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/pkg_resources/__init__.py:2871
  /workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/pkg_resources/__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
- generated xml file: /workdir/results/django-filter/22.1/1/cpython-test-results.xml -
=========================== short test summary info ============================
ERROR tests/test_filtering.py - django.core.exceptions.ImproperlyConfigured: ...
ERROR tests/test_filters.py - django.core.exceptions.ImproperlyConfigured: Re...
ERROR tests/test_filterset.py - django.core.exceptions.ImproperlyConfigured: ...
ERROR tests/test_forms.py - django.core.exceptions.ImproperlyConfigured: Requ...
ERROR tests/test_utils.py - django.core.exceptions.ImproperlyConfigured: Requ...
ERROR tests/test_views.py - django.core.exceptions.ImproperlyConfigured: Requ...
ERROR tests/rest_framework/test_backends.py - django.core.exceptions.Improper...
ERROR tests/rest_framework/test_filterset.py - django.core.exceptions.Imprope...
ERROR tests/rest_framework/test_integration.py - django.core.exceptions.Impro...
!!!!!!!!!!!!!!!!!!! Interrupted: 9 errors during collection !!!!!!!!!!!!!!!!!!!!
======================== 2 warnings, 9 errors in 0.68s =========================
ERROR: InvocationError for command /workdir/django-filter-22.1/.tox/cpythonlibtest-unit-test-tests/bin/pytest -v --tb=native --junitxml /workdir/results/django-filter/22.1/1/cpython-test-results.xml (exited with code 2)
___________________________________ summary ____________________________________
ERROR:   cpythonlibtest-unit-test-tests: commands failed
