GLOB sdist-make: /workdir/slicer-0.0.7/setup.py
cpythonlibtest-unit-test-tests create: /workdir/slicer-0.0.7/.tox/cpythonlibtest-unit-test-tests
cpythonlibtest-unit-test-tests installdeps: mock, pytest
cpythonlibtest-unit-test-tests inst: /workdir/slicer-0.0.7/.tox/.tmp/package/1/slicer-0.0.7.zip
cpythonlibtest-unit-test-tests installed: exceptiongroup==1.2.0,iniconfig==2.0.0,mock==5.1.0,packaging==23.2,pluggy==1.3.0,pytest==7.4.3,slicer @ file:///workdir/slicer-0.0.7/.tox/.tmp/package/1/slicer-0.0.7.zip#sha256=73e073541c41671a9ae2720abe2a68f4744bb3dac9ab317117296534c8997585,tomli==2.0.1
cpythonlibtest-unit-test-tests run-test-pre: PYTHONHASHSEED='2107309633'
cpythonlibtest-unit-test-tests run-test: commands[0] | pytest -v --tb=native --junitxml /workdir/results/slicer/0.0.7/1/cpython-test-results.xml
============================= test session starts ==============================
platform linux -- Python 3.10.8, pytest-7.4.3, pluggy-1.3.0 -- /workdir/slicer-0.0.7/.tox/cpythonlibtest-unit-test-tests/bin/python
cachedir: .tox/cpythonlibtest-unit-test-tests/.pytest_cache
rootdir: /workdir/slicer-0.0.7
collecting ... collected 0 items / 1 error

==================================== ERRORS ====================================
____________________ ERROR collecting slicer/test_slicer.py ____________________
ImportError while importing test module '/workdir/slicer-0.0.7/slicer/test_slicer.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
slicer/test_slicer.py:13: in <module>
    import pandas as pd
E   ModuleNotFoundError: No module named 'pandas'
- generated xml file: /workdir/results/slicer/0.0.7/1/cpython-test-results.xml -
=========================== short test summary info ============================
ERROR slicer/test_slicer.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.13s ===============================
ERROR: InvocationError for command /workdir/slicer-0.0.7/.tox/cpythonlibtest-unit-test-tests/bin/pytest -v --tb=native --junitxml /workdir/results/slicer/0.0.7/1/cpython-test-results.xml (exited with code 2)
___________________________________ summary ____________________________________
ERROR:   cpythonlibtest-unit-test-tests: commands failed
