.package create: /workdir/discord.py-2.1.0/.tox/.package
.package installdeps: setuptools, wheel
warning: check: missing meta-data: if 'author' supplied, 'author_email' should be supplied too

cpythonlibtest-unit-test-tests create: /workdir/discord.py-2.1.0/.tox/cpythonlibtest-unit-test-tests
cpythonlibtest-unit-test-tests installdeps: mock, pytest, -rrequirements.txt
cpythonlibtest-unit-test-tests inst: /workdir/discord.py-2.1.0/.tox/.tmp/package/1/discord.py-2.1.0.tar.gz
cpythonlibtest-unit-test-tests installed: aiohttp==3.9.0,aiosignal==1.3.1,async-timeout==4.0.3,attrs==23.1.0,discord.py @ file:///workdir/discord.py-2.1.0/.tox/.tmp/package/1/discord.py-2.1.0.tar.gz#sha256=772b0fcfe903689354aeefbe0deaa88b6a3bcfb3ab1eec551ad879cc51085f55,exceptiongroup==1.1.3,frozenlist==1.4.0,idna==3.4,iniconfig==2.0.0,mock==5.1.0,multidict==6.0.4,packaging==23.2,pluggy==1.3.0,pytest==7.4.3,tomli==2.0.1,yarl==1.9.3
cpythonlibtest-unit-test-tests run-test-pre: PYTHONHASHSEED='2637690006'
cpythonlibtest-unit-test-tests run-test: commands[0] | pytest -v --tb=native --junitxml /workdir/results/discord.py/2.1.0/1/cpython-test-results.xml
============================= test session starts ==============================
platform linux -- Python 3.10.8, pytest-7.4.3, pluggy-1.3.0 -- /workdir/discord.py-2.1.0/.tox/cpythonlibtest-unit-test-tests/bin/python
cachedir: .tox/cpythonlibtest-unit-test-tests/.pytest_cache
rootdir: /workdir/discord.py-2.1.0
configfile: pyproject.toml
collecting ... collected 164 items / 1 error

==================================== ERRORS ====================================
_____________ ERROR collecting tests/test_annotated_annotation.py ______________
ImportError while importing test module '/workdir/discord.py-2.1.0/tests/test_annotated_annotation.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_annotated_annotation.py:27: in <module>
    from typing_extensions import Annotated
E   ModuleNotFoundError: No module named 'typing_extensions'
=============================== warnings summary ===============================
.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/config/__init__.py:1373
  /workdir/discord.py-2.1.0/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/config/__init__.py:1373: PytestConfigWarning: Unknown config option: asyncio_mode
  
    self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")

tests/test_app_commands_invoke.py:165
  /workdir/discord.py-2.1.0/tests/test_app_commands_invoke.py:165: PytestUnknownMarkWarning: Unknown pytest.mark.asyncio - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.asyncio

tests/test_app_commands_invoke.py:192
  /workdir/discord.py-2.1.0/tests/test_app_commands_invoke.py:192: PytestUnknownMarkWarning: Unknown pytest.mark.asyncio - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.asyncio

tests/test_ext_commands_cog.py:139
  /workdir/discord.py-2.1.0/tests/test_ext_commands_cog.py:139: PytestUnknownMarkWarning: Unknown pytest.mark.asyncio - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.asyncio

tests/test_ext_commands_cog.py:165
  /workdir/discord.py-2.1.0/tests/test_ext_commands_cog.py:165: PytestUnknownMarkWarning: Unknown pytest.mark.asyncio - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.asyncio

tests/test_ext_commands_cog.py:201
  /workdir/discord.py-2.1.0/tests/test_ext_commands_cog.py:201: PytestUnknownMarkWarning: Unknown pytest.mark.asyncio - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.asyncio

tests/test_ext_commands_cog.py:226
  /workdir/discord.py-2.1.0/tests/test_ext_commands_cog.py:226: PytestUnknownMarkWarning: Unknown pytest.mark.asyncio - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.asyncio

tests/test_ext_commands_cog.py:251
  /workdir/discord.py-2.1.0/tests/test_ext_commands_cog.py:251: PytestUnknownMarkWarning: Unknown pytest.mark.asyncio - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.asyncio

tests/test_ext_commands_cog.py:278
  /workdir/discord.py-2.1.0/tests/test_ext_commands_cog.py:278: PytestUnknownMarkWarning: Unknown pytest.mark.asyncio - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.asyncio

tests/test_ext_commands_cog.py:305
  /workdir/discord.py-2.1.0/tests/test_ext_commands_cog.py:305: PytestUnknownMarkWarning: Unknown pytest.mark.asyncio - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.asyncio

tests/test_ext_commands_cog.py:336
  /workdir/discord.py-2.1.0/tests/test_ext_commands_cog.py:336: PytestUnknownMarkWarning: Unknown pytest.mark.asyncio - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.asyncio

tests/test_ext_commands_cog.py:362
  /workdir/discord.py-2.1.0/tests/test_ext_commands_cog.py:362: PytestUnknownMarkWarning: Unknown pytest.mark.asyncio - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.asyncio

tests/test_ext_commands_cog.py:398
  /workdir/discord.py-2.1.0/tests/test_ext_commands_cog.py:398: PytestUnknownMarkWarning: Unknown pytest.mark.asyncio - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.asyncio

tests/test_ext_commands_cog.py:423
  /workdir/discord.py-2.1.0/tests/test_ext_commands_cog.py:423: PytestUnknownMarkWarning: Unknown pytest.mark.asyncio - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.asyncio

tests/test_ext_tasks.py:19
  /workdir/discord.py-2.1.0/tests/test_ext_tasks.py:19: PytestUnknownMarkWarning: Unknown pytest.mark.asyncio - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.asyncio

tests/test_ext_tasks.py:48
  /workdir/discord.py-2.1.0/tests/test_ext_tasks.py:48: PytestUnknownMarkWarning: Unknown pytest.mark.asyncio - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.asyncio

tests/test_utils.py:72
  /workdir/discord.py-2.1.0/tests/test_utils.py:72: PytestUnknownMarkWarning: Unknown pytest.mark.asyncio - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.asyncio

tests/test_utils.py:175
  /workdir/discord.py-2.1.0/tests/test_utils.py:175: PytestUnknownMarkWarning: Unknown pytest.mark.asyncio - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.asyncio

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
- generated xml file: /workdir/results/discord.py/2.1.0/1/cpython-test-results.xml -
=========================== short test summary info ============================
ERROR tests/test_annotated_annotation.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
======================== 18 warnings, 1 error in 0.53s =========================
ERROR: InvocationError for command /workdir/discord.py-2.1.0/.tox/cpythonlibtest-unit-test-tests/bin/pytest -v --tb=native --junitxml /workdir/results/discord.py/2.1.0/1/cpython-test-results.xml (exited with code 2)
___________________________________ summary ____________________________________
ERROR:   cpythonlibtest-unit-test-tests: commands failed
